# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
  pod 'SDWebImage', '~>3.8'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
